### ISSUE TITLE
Requesting  Error Poloniex

### ISSUE THREAD

**Issue by MrLending** [BitBotFactory/MikaLendingBot#606]
Hello,
the bot works for me since years on Poloniex, but today I got this error 

Error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> Requesting returnOpenLoanOffers
Caught <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> Requesting returnOpenLoanOffers from Poloniex, ignoring.

I try the latest version of the bot but there a even more errors:
```
cd '/Users/XX/Documents/poloniexlendingbot-master/' && '/usr/bin/pythonw'  '/Users/XX/Documents/poloniexlendingbot-master/lendingbot.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/XX/Documents/poloniexlendingbot-master/lendingbot.py", line 17, in <module>
    from modules.ExchangeApiFactory import ExchangeApiFactory
  File "//Users/XX/Documents/poloniexlendingbot-master/modules/ExchangeApiFactory.py", line 6, in <module>
    from modules.Bitfinex import Bitfinex
  File "/Users/XX/Documents/poloniexlendingbot-master/modules/Bitfinex.py", line 6, in <module>
    import requests
ImportError: No module named requests

```
The config has the correct infos.  So I have no idea to solve the problem. Please help.

Regards

**Comment by WesleyThurner** [comment]
To solve your issue with running the latest version, just follow the docs for installing.  It may have changed since the last time you used it.

http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#installing-on-a-computer

Specifically, it looks like your missing this step:

pip install -r requirements.txt

**Comment by MrLending** [comment]
Thanks for fast answering, I installed requirements.txt, but still not working, now the error looks like : 

/Users/XX/poloniexlendingbot-master/poloniexlendingbot-master/' && '/usr/bin/pythonw'  '/Users/XX/poloniexlendingbot-master/poloniexlendingbot-master/lendingbot.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/XX/poloniexlendingbot-master/poloniexlendingbot-master/lendingbot.py", line 17, in <module>
    from modules.ExchangeApiFactory import ExchangeApiFactory
  File "/Users/XX/poloniexlendingbot-master/poloniexlendingbot-master/modules/ExchangeApiFactory.py", line 6, in <module>
    from modules.Bitfinex import Bitfinex
  File "/Users/XX/poloniexlendingbot-master/poloniexlendingbot-master/modules/Bitfinex.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by MrLending** [comment]
No solution yet, updatet all SSL certif etc. Bot working on pythonanayware com but this not my fav. way. Keep searching for solution.

**Comment by MrLending** [comment]
The problem is OSX using the old SSL Certi,  updated it via brew with brewed openssl but python still use the old ssl. No idea yet...

**Comment by WesleyThurner** [comment]
This is one way to fix it, may have to remove the openssl that ships his MacOS :
brew uninstall openssl
brew install openssl

**Comment by Evanito** [comment]
Does above solution fix it for you? @MrLending

**Comment by NMajernik** [comment]
This did not resolve it for me.

**Comment by laxdog** [comment]
Are you trying to run this on python 3.6 @MrLending ?
