### ISSUE TITLE
[Feature] hard minimum when using frrasmin

### ISSUE THREAD

**Issue by Bonez0r** [BitBotFactory/MikaLendingBot#636]
If i understand correctly, if i use frrasmin/frrdelta then mindailyrate is ignored. I would like to use frrdelta, but with a hard minimum, so that when the frr is ridiculously low i don't lend anything.

**Comment by utdrmac** [comment]
According to this [line in the code](https://github.com/BitBotFactory/MikaLendingBot/blob/13d6cb10a1c064d5930456497c15bee1fe89a255/modules/Lending.py#L277), mindailyrate is always the absolute lowest the rate can be. So, if frr+yourDelta < mindailyrate, it will use mindailyrate.

**Comment by Bonez0r** [comment]
You're right, i just tested it. So the mindailyrate IS the hard minimum. Thanks. Issue closed.
