### ISSUE TITLE
Feature request: save log messages in json file between restarts

### ISSUE THREAD

**Issue by yura-pakhuchiy** [BitBotFactory/MikaLendingBot#91]
At present log messages are  lost during bot restart (eg., after configuration update). It would be great if bot will append messages to the previous log, instead of clearing it.

**Comment by rnevet** [comment]
I don't find the old log interesting but I'll add additional information in case someone wants to implement this.

The json log file is written entirely from the bot memory, so if the bot is restarted the history is just gone and overwritten on the first write, no "clearing" is done.

One possible way to implement such a feature would be to load back the "old" json log file (if it there is one) on bot start.

**Comment by lvdhoorn** [comment]
The old log could be interesting for the yearly rates. After a restart the rate is based on the new loans and the history is gone. It would be nice to have a complete history.

**Comment by chfast** [comment]
I have the opposite issue with the log, it is getting large very quickly and web interface is not able to load it. The workaround is to restart the bot to empty it.

**Comment by rnevet** [comment]
@chfast, it's a bug in the recent versions.

**Comment by chfast** [comment]
Should I create a separated bug report for it?

Anyway, this feature request propose the log to grow indefinitely. Maybe instead the bot could dump some aggregates statistics in separate log/logs. Like one day summary...

**Comment by rnevet** [comment]
Regarding the bug, we'll fix it ASAP.

**Comment by yura-pakhuchiy** [comment]
@rnevet BTW, `startWebServer` option is broken as well. It always starts when this option is present in config file, the only way to disable it, is to comment line with it.

**Comment by yura-pakhuchiy** [comment]
@rnevet both problems was introduced in 951f9b6276c2e31d7179199b3247f74ea9f2cc7a
Also this commit breaks backwards compatibility: if `sixtydaythreshold` is set, bot complains:
`ERROR: xdaythreshold is not allowed to be left unset. Please check your config.`

**Comment by laxdog** [comment]
I actually do think this should be done, though it should be through a rewrite to the logging module to use it as a proper python logger with all the handlers you want and config for rotation etc. 

You could then have the botlog, an actual log (this issue) and print to stdout.
